# Generated by Django 5.0.7 on 2024-07-21 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbitraceweb', '0004_alter_missingperson_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254XXXXXXXXX' or '07XXXXXXXX' or '01XXXXXXXX'. Up to 13 digits allowed.", regex='^(?:\\+254|0)[17]\\d{8}$')]),
        ),
    ]
