# Generated by Django 5.0.7 on 2024-07-21 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbitraceweb', '0005_tip_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='x_username',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='X username must be up to 15 characters long and can only contain letters, numbers, and underscores.', regex='^@?(\\w){1,15}$')]),
        ),
    ]
